git_prompt_info() {
  ref=$(git-symbolic-ref HEAD 2> /dev/null) || return
  echo "(%{$fg[yellow]%}git:${ref#refs/heads/}%{$fg[blue]%})"
}

autoload -U colors
colors

setopt prompt_subst

export PROMPT=$'%{$fg[blue]%}%m%{\e[0;34m%}%~$(git_prompt_info)$ %{\e[0m%}'

# command aliases

alias ss='ruby script/server'
alias sc='ruby script/console'
alias db='ruby script/dbconsole'
alias ls='ls -aGl'

# project aliases

alias kc='cd ~/Projects/kudocities/trunk'
alias jgp='cd ~/Projects/jgp/aspire/trunk'

# history file

setopt histignoredups

# source $HOME/.rake_completion.zsh

cd ~/Projects

bindkey '^H' backward-delete-char
bindkey "^[[3~" delete-char

os=`uname -a`

case $os in
  *Darwin*)
    source ~/.houseshare/zsh/apple
  ;;;
esac


setopt autocd