#!/usr/bin/env bash

if test ! $(which brew); then
  /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
fi

brew tap Homebrew/bundle
brew bundle --no-upgrade

mkdir -p $HOME/config/fish
ln -Fs $HOME/.dotfiles/config/fish/config.fish $HOME/.config/fish/config.fish
ln -Fs $HOME/.dotfiles/config/fish/functions   $HOME/.config/fish/functions
ln -Fs $HOME/.dotfiles/config/fish/completions $HOME/.config/fish/completions
ln -Fs $HOME/.dotfiles/config/fish/conf.d      $HOME/.config/fish/conf.d

shell="/usr/local/bin/fish"

if test ! $(grep $shell /etc/shells); then
  sudo bash -c "echo $shell >> /etc/shells"
fi

if [[ ! $SHELL = $shell ]]; then
  chsh -s $shell
fi

dotfilesInstall=true fish