#!/usr/bin/env zsh

changes=$(git ls-files --exclude-per-directory=.gitignore --exclude-from=.git/info/exclude --others --modified -t)
count=$(echo $clean | wc -l | tr -d ' ')
case $count in
  0)
  ;;;
  
  *)
    echo '*'
  ;;;
esac