#!/usr/bin/env bash

set -e

icloudPath="$HOME/.icloud"
[ ! -L $icloudPath ] && ln -s "$HOME/Library/Mobile Documents/com~apple~CloudDocs" $icloudPath
[ ! -L $HOME/.dotfiles ] && ln -s "$HOME/Library/Mobile Documents/com~apple~CloudDocs/dotfiles" $HOME/.dotfiles

$HOME/.dotfiles/install